import 'package:tjara/app/models/media_model/media_model.dart';
import 'package:tjara/app/models/products/products_model.dart';

final demoProducts = ProductModel(
  products: Products(
    currentPage: 1,
    data: [
      ProductDatum(
        id: "1",
        name: "Wireless Headphones",
        slug: "wireless-headphones",
        description:
            "High-quality over-ear wireless headphones with noise cancellation.",
        stock: 20,
        price: 7999,
        salePrice: 6999,
        isFeatured: 1,
        isDeal: 1,
        productType: "Electronics",
        productGroup: "Audio",
        status: "active",
        createdAt: DateTime.now().subtract(const Duration(days: 3)),
        updatedAt: DateTime.now(),
        isDiscountProduct: true,
        thumbnail: Thumbnail(
          media: MediaUniversalModel(
            id: "t1",
            url: "https://via.placeholder.com/300x300.png?text=Headphones",
            mediaType: "image",
            createdAt: DateTime.now(),
            updatedAt: DateTime.now(),
          ),
        ),
        shop: DatumShop(
          shop: ShopShop(
            id: "s1",
            name: "GadgetZone",
            slug: "gadget-zone",
            description: "Top quality electronics and gadgets",
            isVerified: 1,
            isFeatured: 1,
            createdAt: DateTime.now().subtract(const Duration(days: 100)),
            updatedAt: DateTime.now(),
          ),
        ),
        meta: DatumMeta(
          views: "1245",
          sold: "300",
          is_featured: 1,
          gallery: "",
          recent_buyer: "Ali",
        ),
      ),
      ProductDatum(
        id: "2",
        name: "Smart Watch",
        slug: "smart-watch",
        description:
            "Waterproof smartwatch with fitness tracker, heart rate monitor, and GPS.",
        stock: 12,
        price: 9999,
        salePrice: 8499,
        isFeatured: 0,
        isDeal: 0,
        productType: "Electronics",
        productGroup: "Wearables",
        status: "active",
        createdAt: DateTime.now().subtract(const Duration(days: 7)),
        updatedAt: DateTime.now(),
        isDiscountProduct: true,
        thumbnail: Thumbnail(
          media: MediaUniversalModel(
            id: "t2",
            url: "https://via.placeholder.com/300x300.png?text=Smart+Watch",
            mediaType: "image",
            createdAt: DateTime.now(),
            updatedAt: DateTime.now(),
          ),
        ),
        shop: DatumShop(
          shop: ShopShop(
            id: "s2",
            name: "TechWorld",
            slug: "tech-world",
            description: "Your one-stop tech store.",
            isVerified: 1,
            isFeatured: 0,
            createdAt: DateTime.now().subtract(const Duration(days: 50)),
            updatedAt: DateTime.now(),
          ),
        ),
        meta: DatumMeta(
          views: "980",
          sold: "100",
          is_featured: 0,
          recent_buyer: "Ahmed",
        ),
      ),
      ProductDatum(
        id: "3",
        name: "Organic Cotton T-Shirt",
        slug: "organic-cotton-tshirt",
        description:
            "100% organic cotton t-shirt, comfortable and eco-friendly.",
        stock: 50,
        price: 1999,
        salePrice: 1499,
        isFeatured: 1,
        isDeal: 1,
        productType: "Clothing",
        productGroup: "Men's Fashion",
        status: "active",
        createdAt: DateTime.now().subtract(const Duration(days: 10)),
        updatedAt: DateTime.now(),
        isDiscountProduct: true,
        thumbnail: Thumbnail(
          media: MediaUniversalModel(
            id: "t3",
            url: "https://via.placeholder.com/300x300.png?text=T-Shirt",
            mediaType: "image",
            createdAt: DateTime.now(),
            updatedAt: DateTime.now(),
          ),
        ),
        shop: DatumShop(
          shop: ShopShop(
            id: "s3",
            name: "EcoFashion",
            slug: "eco-fashion",
            description: "Sustainable fashion for conscious consumers",
            isVerified: 1,
            isFeatured: 1,
            createdAt: DateTime.now().subtract(const Duration(days: 200)),
            updatedAt: DateTime.now(),
          ),
        ),
        meta: DatumMeta(
          views: "850",
          sold: "200",
          is_featured: 1,
          recent_buyer: "Sarah",
        ),
      ),
      ProductDatum(
        id: "4",
        name: "Stainless Steel Water Bottle",
        slug: "steel-water-bottle",
        description:
            "Insulated stainless steel bottle that keeps drinks cold for 24 hours.",
        stock: 35,
        price: 2499,
        salePrice: 1999,
        isFeatured: 0,
        isDeal: 0,
        productType: "Home & Kitchen",
        productGroup: "Kitchenware",
        status: "active",
        createdAt: DateTime.now().subtract(const Duration(days: 15)),
        updatedAt: DateTime.now(),
        isDiscountProduct: false,
        thumbnail: Thumbnail(
          media: MediaUniversalModel(
            id: "t4",
            url: "https://via.placeholder.com/300x300.png?text=Water+Bottle",
            mediaType: "image",
            createdAt: DateTime.now(),
            updatedAt: DateTime.now(),
          ),
        ),
        shop: DatumShop(
          shop: ShopShop(
            id: "s4",
            name: "HomeEssentials",
            slug: "home-essentials",
            description: "Quality products for your home",
            isVerified: 1,
            isFeatured: 0,
            createdAt: DateTime.now().subtract(const Duration(days: 150)),
            updatedAt: DateTime.now(),
          ),
        ),
        meta: DatumMeta(
          views: "650",
          sold: "150",
          is_featured: 0,
          recent_buyer: "Mohammed",
        ),
      ),
      ProductDatum(
        id: "5",
        name: "Yoga Mat",
        slug: "yoga-mat",
        description: "Non-slip, eco-friendly yoga mat with carrying strap.",
        stock: 18,
        price: 3499,
        salePrice: 2999,
        isFeatured: 1,
        isDeal: 1,
        productType: "Sports",
        productGroup: "Fitness",
        status: "active",
        createdAt: DateTime.now().subtract(const Duration(days: 5)),
        updatedAt: DateTime.now(),
        isDiscountProduct: true,
        thumbnail: Thumbnail(
          media: MediaUniversalModel(
            id: "t5",
            url: "https://via.placeholder.com/300x300.png?text=Yoga+Mat",
            mediaType: "image",
            createdAt: DateTime.now(),
            updatedAt: DateTime.now(),
          ),
        ),
        shop: DatumShop(
          shop: ShopShop(
            id: "s5",
            name: "FitLife",
            slug: "fit-life",
            description: "Everything for your fitness journey",
            isVerified: 1,
            isFeatured: 1,
            createdAt: DateTime.now().subtract(const Duration(days: 180)),
            updatedAt: DateTime.now(),
          ),
        ),
        meta: DatumMeta(
          views: "1100",
          sold: "250",
          is_featured: 1,
          recent_buyer: "Aisha",
        ),
      ),
      ProductDatum(
        id: "6",
        name: "Bluetooth Speaker",
        slug: "bluetooth-speaker",
        description: "Portable waterproof speaker with 20-hour battery life.",
        stock: 25,
        price: 5999,
        salePrice: 4999,
        isFeatured: 1,
        isDeal: 1,
        productType: "Electronics",
        productGroup: "Audio",
        status: "active",
        createdAt: DateTime.now().subtract(const Duration(days: 8)),
        updatedAt: DateTime.now(),
        isDiscountProduct: true,
        thumbnail: Thumbnail(
          media: MediaUniversalModel(
            id: "t6",
            url: "https://via.placeholder.com/300x300.png?text=Speaker",
            mediaType: "image",
            createdAt: DateTime.now(),
            updatedAt: DateTime.now(),
          ),
        ),
        shop: DatumShop(
          shop: ShopShop(
            id: "s1",
            name: "GadgetZone",
            slug: "gadget-zone",
            description: "Top quality electronics and gadgets",
            isVerified: 1,
            isFeatured: 1,
            createdAt: DateTime.now().subtract(const Duration(days: 100)),
            updatedAt: DateTime.now(),
          ),
        ),
        meta: DatumMeta(
          views: "1350",
          sold: "400",
          is_featured: 1,
          recent_buyer: "Omar",
        ),
      ),
      ProductDatum(
        id: "7",
        name: "Leather Wallet",
        slug: "leather-wallet",
        description:
            "Genuine leather wallet with multiple card slots and RFID protection.",
        stock: 30,
        price: 1799,
        salePrice: 1499,
        isFeatured: 0,
        isDeal: 0,
        productType: "Accessories",
        productGroup: "Men's Accessories",
        status: "active",
        createdAt: DateTime.now().subtract(const Duration(days: 20)),
        updatedAt: DateTime.now(),
        isDiscountProduct: false,
        thumbnail: Thumbnail(
          media: MediaUniversalModel(
            id: "t7",
            url: "https://via.placeholder.com/300x300.png?text=Wallet",
            mediaType: "image",
            createdAt: DateTime.now(),
            updatedAt: DateTime.now(),
          ),
        ),
        shop: DatumShop(
          shop: ShopShop(
            id: "s6",
            name: "ClassicAccessories",
            slug: "classic-accessories",
            description: "Premium accessories for men and women",
            isVerified: 1,
            isFeatured: 0,
            createdAt: DateTime.now().subtract(const Duration(days: 120)),
            updatedAt: DateTime.now(),
          ),
        ),
        meta: DatumMeta(
          views: "720",
          sold: "180",
          is_featured: 0,
          recent_buyer: "Khalid",
        ),
      ),
      ProductDatum(
        id: "8",
        name: "Ceramic Coffee Mug Set",
        slug: "ceramic-mug-set",
        description:
            "Set of 4 ceramic mugs with elegant designs, microwave safe.",
        stock: 15,
        price: 2999,
        salePrice: 2499,
        isFeatured: 1,
        isDeal: 1,
        productType: "Home & Kitchen",
        productGroup: "Kitchenware",
        status: "active",
        createdAt: DateTime.now().subtract(const Duration(days: 12)),
        updatedAt: DateTime.now(),
        isDiscountProduct: true,
        thumbnail: Thumbnail(
          media: MediaUniversalModel(
            id: "t8",
            url: "https://via.placeholder.com/300x300.png?text=Coffee+Mugs",
            mediaType: "image",
            createdAt: DateTime.now(),
            updatedAt: DateTime.now(),
          ),
        ),
        shop: DatumShop(
          shop: ShopShop(
            id: "s4",
            name: "HomeEssentials",
            slug: "home-essentials",
            description: "Quality products for your home",
            isVerified: 1,
            isFeatured: 0,
            createdAt: DateTime.now().subtract(const Duration(days: 150)),
            updatedAt: DateTime.now(),
          ),
        ),
        meta: DatumMeta(
          views: "890",
          sold: "220",
          is_featured: 1,
          recent_buyer: "Fatima",
        ),
      ),
    ],
  ),
);
